title: CAIO
description: City–AI Coevolution
theme: minima

url: "https://www.caio-project.it"
baseurl: ""

header_pages:
  - about.md
  - people.md
  - publications.md
  - press-coverage.md
  - contact.md
